export { IError } from './interface';
import { Workspace } from './workspace';
export { StampConfig, configuration } from './utils';
export { Deployment, DeploymentInstanceInfo, RegistrationResult } from '@kumori/admission-client';
export { ComponentConfig } from './component';
export { ServiceConfig } from './service';
export { DeploymentConfig } from './deployment';
export { RuntimeConfig } from './runtime';
export { ResourceConfig } from './resource';
export declare const workspace: Workspace;
