"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const component_1 = require("./component");
const deployment_1 = require("./deployment");
const service_1 = require("./service");
const resource_1 = require("./resource");
const localstamp_1 = require("./localstamp");
const runtime_1 = require("./runtime");
const workspace_1 = require("./workspace");
const project_1 = require("./project");
const stamp_1 = require("./stamp");
var utils_1 = require("./utils");
exports.configuration = utils_1.configuration;
var admission_client_1 = require("@kumori/admission-client");
exports.Deployment = admission_client_1.Deployment;
exports.DeploymentInstanceInfo = admission_client_1.DeploymentInstanceInfo;
exports.RegistrationResult = admission_client_1.RegistrationResult;
const stamp_manager_1 = require("./stamp-manager");
exports.workspace = new workspace_1.Workspace(new component_1.Component(), new deployment_1.Deployment(), new localstamp_1.LocalStamp(), new runtime_1.Runtime(), new service_1.Service(), new resource_1.Resource(), new project_1.Project(), new stamp_1.Stamp(new stamp_manager_1.StampStubFactoryImpl()));
//# sourceMappingURL=index.js.map